public enum Information {

    USER_INVALID,
    PWD_INVALID,
    CREDENTIALS_INCORRECT,
    USER_NOT_FOUND,
    BROADCAST_NOT_FOUND,
    NOT_FOUND,
    ARGUMENTS_MISSING,
    BROADCAST_CREATED,
    ILLEGAL_NAME,
    EXISTS,
    ADDED,
    REMOVED,
    NOT_A_MEMBER,
    CONNECTION_FAILED,
    UNKNOWN,
    DELETED;


}
